[package]
name = "rstrt"
version.workspace = true
edition = "2024"
description = "A safe, ergonomic Rust wrapper over NVIDIA TensorRT"
license = "MIT"
repository = "https://github.com/keithyin/rstrt"

[dependencies]
rstrt-sys = { path = "../rstrt-sys", version = "0.3.0" }
ndarray = "0.16"
thiserror = "2"
half = "2"
